label day2_Kirana:

    scene kamar
    "Sepertinya aku sudah mulai terbiasa dengan pagi hari ini"
    "~Suara Kentut~"
    "Aakkhh.. perutku sakit seperti gara-gara kemarin makan terlalu banyak"

    scene kamar mandi

    scene ruang keluarga 
    "Hmm.. ada yang bersihin motor"

    scene depan rumah
    mc "Ayah pagi-pagi udah rajin aja nih hehhe"
    dad "loh, nakkk sudah bangun, kok tumben kamu ga bangkong"
    mc "kan tiap pagi emang bangun pagi kan hhaha"
    mc "kalau gitu aku siap siap dulu buat berangkat sekolah"
    dad "Iyaa nak"

    scene dapur
    mom "Makanan Sudah Siap !"

    scene depan rumahh
    dad "Iyaa Bu.."

    scene kamar mandi 
    mc "Iyaa"
    "Aku harus bergegas memakai baju"

    scene dapur
    mom "Sudah selesai siapin untuk ke sekolah ?"
    mc "Sudah bu"
    dad "[mcFirst] Sini [mom] sudah selesai masak nih, enak lohh!! ayo makan"
    mc "Iyaa yah"
    mc "Bu aku kok lapar banget ya ?"
    mom "Soalnya kemarin kamu langsung tidur dan ga bangun-bangun"
    mom "[mom] ga mau ganggu bangunin juga sepertinya kemarin kamu kecapekan"
    mom "Oiya,, Ibu sudah siapinn juga nasinya"
    mc "Hoo,, jadi begitu. Makasih bu sudah disiapin juga, kalau gitu [mcFirst] makan dulu bu"
    mom "Kemarin, cewe itu siapamu ?"
    dad "Ehhh.. Kemarin [mcFirst] bawa cewe kerumah ?"
    dad "Ho ho ho ho ho"
    mc "...."
    mc "Dia hanya teman sekolah"
    ai "Beneran teman sekolah ? hehehe"
    mc "Iyaa hanya teman sekolah saja, tapi sepertinya dia dulu juga 1 smp denganku"
    mc "Soalnya kemarin [mg2_Last] sempat bertanya masalah bullying"
    mom "Hmm.. jadi begitu"
    mc "Terus dia juga memaksaku dan mengikuti jalan. Kalau ingin mengantarku sampai kerumaku sekalian biar tau rumahnya yang mana"
    mc "Karena merepotkan akhirnya aku terima aja tawarannya"
    mom "Hahaha iya iya, Ibu percaya kok cuma tadi mau bercandain [mcFirst] aja"
    mom "Soalnya, Ibu sempat kaget kalau kamu tiba-tiba bawa teman kerumah"
    dad "Ayah juga kaget loh dengar kamu bawa cewe kemarin"
    mom "Ibu kemarin sempat bahagia kalau kamu mulai sedikit membaik"
    mc "hahahaha Iyaa bu"
    mc "Oiya, [cat] Kemana bu ?"
    mom "Itu Lagi Makan juga"
    mc "Tumben ga kekamarku kayak kemarin kemarinnya"
    dad "Soalnya [dad] kemarin waktu pulang langsung main sama [cat]"
    dad "Ibu juga ikutan hehehe"
    mc "Pagi [cat] makanmu lahap bener"
    cat "Nyaaa "
    mc "Aku Cuci piring dulu ya bu setelah itu berangkat langsung"
    mom "Oiya, Bekalnya sudah [mom] siapkan ada disini"
    mc 'Iya bu'
    "~Cuci Piring~"
    mc "Kalau gitu aku berangkat dulu Ayah Ibu"
    ai "Iyaa Nak hati hati dijalan"
    mc "Okie"
    mom "Ayah ga berangkat kerja juga ?"
    dad "Bentar lagi, berangkat"

    scene gerbang sekolah 
    "Hmm.. ada yang mendekatiku mungkin sebaiknya aku diamin saja"
    $ kg = "Ketua Geng Kaya"
    $ ag = "Anggota Gengs Kaya"
    kg "yauda lah ya ga cocok masuk gengs kita tuh sudah miskin dan tercium bau bau ga mampu"
    kg "Benar ga gengs"
    ag "Yup, Ketua emang bener emang best kaum miskin kek gini mana bisa masuk geng ini. Dih.."
    na "Oeee [mcFirst] Tunggu aku!!!"
    "Untunglah ada si Bodoh satu ini jadi aku bisa melewati masalah ini"
    na "Siapa itu ? [mcFirst]"
    mc "Ga tau juga aku, Mungkin kakak kelas gabut"
    mc "Abaikan aja"
    na "Hahaha, Okay dah langsung kelas aja kuy"
    kg "Hei,, kalian mengabaikanku yaa awas aja kalian dasar kaum miskin"

    scene lorong
    mg2 "Ada [mcFirst], aku kesana dulu gaes"
    ol "Hooo sudah ada incaran nih"
    mg2 "Ehh Ngga lah. Cuma teman itu"
    ol "Iyaa dah kalau gitu sana selamat sukses.. "
    ol "Ciiee ciiee"
    mg2 "Ihh Apaan sih kalian ?"
    ol "Hahahhaha,, dah dah sana"
    "Kayaknya ada yang mau mendekat"
    mg2 "Baa.."
    mc "Astaga.."
    mg2 "Kaget ga ?"
    mc "Hmmm..."
    na "Lahh,, ada kamu [mg2_Last] aku ikutan kaget juga njirr"
    mg2 "Hehehe maaf maaf.. "
    mg2 "Gitu aja marah Te hee"

    scene kelas
    na "Kuy Duduk"
    mc "Duduk disebelahku lagi ?"
    mg2 "Ga suka ?"
    na "Akhir Akhir ini [mg2_Last] duduk ama [mcFirst] mulu"
    na "Ciiiee ciiee ada apa ini ?"
    mc "Entahlah"
    mg2 "padahal baru 2 hari"
    mc "Hmmm..."
    mg2 "Mending sekarang kita belajardeh sampai bel berbunyi hahaha"
    "~Ding Dong~"
    sr "Selamat Pagi anak-anak sudah kah siap untuk belajar hari ini ?"
    sk "Tidak bu!!"
    sr "Kalau gitu tidur aja yaa "
    wkk "Ihh Bu Senda.. Kami Bercanda bu"
    sr "Sama Ibu juga Hahahaha"
    sk "Astaga..."
    sr "yaudah kita mulai saja biar cepat selesai setelah itu biar santai-santai sambil nunggu bel istirahat"
    sk "Baiik bu!"
    "~Materi Fungi lanjutan~"
    "~Ding Dong~"
    sr "Sudah bel Anak- anak kalau gitu selamat istirahat anak"
    sk "Yeay sudah istirahat"
    ol "[mg2_Last] ga pergi ke kantin ?"
    mg2 "Iyaa bentar"
    mg2 "[mcFirst] ga mau pergi ke kantin juga ?"
    mc "Ga usah aku soalnya bawa bekal"
    mg2 "dihh mauu buatan Ibumu"
    mc "Emohh.. sana ikut temanmu ke kantin"
    na "Bro Ikutan juga bareng kita ? [skco1] dan [wkk]"
    mc "Ga, duluan dah"
    na "Oke kalau begitu, Lets go kawand"
    wkk "Okay ma brader"
    "Isi Bekalnya lumayan banyak juga"
    "Nyam Nyam Nyam~"
    "Kenyang juga, aku pikir akan porsi kecil ternya porsi besar"
    "~Ding Dong~"
    mg2 "Fuhaah Kenyangnyaa~"
    na "Aku Masih kurang"
    wkk "Hahaha Bisa aja kamu"
    skco1 "Sama sih aku masih kurang soalnya aku ga sarapan sama sekali"
    na "Ini lur kubawakan Roti Sosis"
    mc "Gratis Nih ?"
    na "Bayar dong"
    mc "Ok ok"
    na "Ehh.. gratis gratis aku cuma bercanda hahahah"
    mc "Nih uangnya ambil aja"
    na "Okelah kalau gitu hehehhe"
    mg2 "Punyaku mana ?"
    na "ga ada lah ya beli sendiri dong"
    mg2 "Dih Curang"
    mc "pfft.."
    mg2 "Ihh Ngeledek yaa"
    mc "ga sama sekali"
    na "Hahah lucu sekali melihat kalian berdua. yaudah aku kembali ke bangku dulu"
    na "Ntar Bu Senda keburu datang"
    sr "Selamat siang anak-anak. Ibu punya soal buat kalian dikerjakan yaa! nanti ibu tinggal ke ruang guru soalnya ada rapat"
    $ kk = "Ketua Kelas"
    sr "oiyaa anak anak, kali ini ibu akan membentuk kalian kelompok, tapi sebangku aja ya biar gampang"
    kk "bu apakah sebaiknya di kocok sajaa biar Adil"
    sr "bagaimana apa kalian setuju?"
    sk "Setujuu Bu!! Biar lebih mengenal karakterisitik semuanya bu"
    "Padahal Aku tidak setuju tapi karen akurang suara apa boleh buat"
    kk "Bikin potongan kertas sesuai Absen bu Nanti anak-anak mengambilnya nomor yang diambil akan berkelompok"
    kk "Setelah itu yang sudah mendapatkan kelompok tidak perlu mengambil nomornya lagi bu"
    sr "Tapi nanti anak-anak nomor absen belakang tidak akan kebagian mengambil juga"
    sr "Aha.. Ibu punya ide kita mulai dari nomor absen awal yang mengambil selanjutnya nomor absen terakhir yang mengambil"
    sr "Bagaimana anak-anak ?"
    skco1 "Boleh juga itu bu"
    sr "Okee.. Laksanakan"
    sk "Yes Mam"
    "Ahh Kelompok Merepotkan sekali"
    "Moga dapat orang yang ga merepotkan"
    $ rr = "Rere"
    rr "aku sekelompok sama nomor 3 , siapa absenn nomo 3?"
    mc "Aku"
    rr "Oh Ok"
    mc "...."
    na "Kamu kelompokan sama [rr] lur. orangnya itu Nakal, Males, Sok Cool"
    na "tapi cantik juga sih hehehe"
    mc "Bodoh amat ama yang namanya cantik"
    na "aku dengar-dengar gitu sih dari teman yang 1 SMP dengannya"
    na "Oiyaa, orangnya juga pintar soalnya sering juara aku denger dengernya gitu"
    mc "dahlah. nth ini beruntung atau merugikanku"
    mg2 "hussh!!"
    "Berlanjutlah pemilihan kelompok" 
    sr "Sudah dapat kelompoknya masing masing kan ya ?"
    sr "Kalau gitu Ibu ke ruang guru dulu ya. Soalnya jangan lupa dikerjakan loh"
    sr "kalau ada yang ga ngerjakan ada hukumannya"
    sk "Baik buu"
    na "Aku kelompokan sama Meta anjir, kamu tau sendiri ceriwisnya minta ampun kan itu kzl .. "
    $ mt = "Meta"
    mg2 "Hahaha sabar"
    $ tmn_mg2 = "Filo"
    ol "[mg2_Last]Kelompokan sama siapa kamu ?"
    mg2 "Aku sama [skce2] kalau kamu sama siapa [ol]?"
    ol "Aku sama [kk]"
    skce1 "Ihh.. enak banget"
    mc "Dah dah biar kelar duduk sekelompok sekarang"
    "Mungkin aku sebaiknya kesana"
    rr "...."
    "Ternyata cukup merepotkan juga ya"
    mc "Ayo kerjakan tugasnya bersama"
    rr "ha?kamu aja sono yang ngerjakan, males aku tu, cape mau tidur aja"
    mc "Ini tugas kelompok"
    rr "Serah serah aku lah"
    mc "...."
    "Beberapa Soal ada yang ga kuisi. Lumayan susah juga"
    rr "Kamu ga bisa jawabnya ?"
    mc "Kamu tau jawabannya ?"
    rr "iya, sini dah, aku coba dulu"
    mc 'Terima Kasih'
    "~1 Jam Kemudian~"
    "~Ding Dong~"
    wkk "haa Akhirnya Pulang juga"
    kk "Tugasnya kumpulkan ke meja depan ya"
    na "Baik pak [kk] hahaha"
    kk "Kalau gitu [na] ikut aku juga ke ruang guru nyerahin tugas ini"
    na "dihh... Emohh"
    kk "Ku Geret kao"
    na "Ehh.. Iya iyaa"
    mg2 "Haa capeknya Pusing lagi"
    mc "...."
    mc "Mau Mampir rumahku lagi ?"
    mg2 "Mauuu.. Enakk makanan gratis"
    mg2 "umm. Maksudku main main sama [cat] hehehhe"
    mc "...."
    mc "Yaudah Ayo, kutunggu di depan gerbang ya"
    mg2 "Okie"

    scene gerbang sekolah
    skce1 "Aduuhh aku bareng siapa ya ?"
    skce1 "Aku ga dijemput lagi mana rumahku jauh"
    mc "Rumahmu dimana ?"
    skce1 "Astaga bikin kaget saja [mcFirst]"
    skce1 "Ohh rumahku ada di dekatnya Lippo. Kenapa emangnya ?"
    mc "Hmm. si Arda rumahnya dekat situ"
    mc "aku ada saran Bagaimana Kalau kamu pulangnya sama Arda aja soalnya sejalur dan rumahnya didekat situ juga"
    skce1 "Tapi mau ga ya ?"
    mc "Coba aja dulu"
    mg2 "Lets go Rumahmu [mcFirst]"
    mc "Maaf hari ini ga bisa"
    mg2 "Lahh.. kenapa ?"
    mc "Mungkin Next time saja lah kalau mau main sama [cat]"
    mg2 "Hmm.. Yaudah kalau gitu aku pulang dulu aja dah"
    mc "Wait, ada yang mau ikut kamu pulang juga"
    mg2 "Sapa ?"
    skce1 "Aku Na, boleh Nebeng juga ga ?"
    skce1 "Kebetulan rumahku dekat sama rumahmu sepertinya"
    mg2 "Hmm.. Okelah kalau gitu"
    skce1 "Wah.. Thanks [mg2_Last]"
    mg2 "No Problem"
    mg2 "Kalau gitu aku balik duluan ya [mcFirst]"
    mc "oh ok"

    scene depan rumah 
    mc "Aku Pulang !"

    scene ruang keluarga 
    mc "Ibu Kenapa keliatannya letih banget"
    mom "Iyaa habis main sama [cat] terus ngadem didepan kipas sama nonton tv"
    mom "Kayaknya [mom] masuk angin"
    mc "Kalau gitu aku yang siapin Makan malam nanti"
    mc "[cat] dimana ?"
    mom "itu tidur di kamarmu"
    mc "oh ok. kalau gitu Ibu istirahat dulu aja"
    mom "Iyaa"

    scene kamar
    mc "Enak banget tidurmu [cat]"
    cat "Fuurr.. Furrr"
    mc "dahlah Aku tidur juga"

    scene kamar malam
    cat "Meooow Meeooow"
    mc "Hoaam.. dah bangun kau [cat]"
    cat "Nyaaa~"
    mc "Sudah Malam juga kalau gitu aku siapin makanan untuk makan malam"

    scene dapur
    mc "[cat] Makanan mu sudah kusiapin makan sini"
    cat "Nyaaa Nyaa~"
    "Hmm.. Masak apa enaknya ya ? atau aku masak random saja lah"
    "~Beberapa jam kemudian~"
    mc "Ibuu!! sudah siapp makanannya"
    mom "Iyaa Nak"
    mc "Gimana [mom] sudah enakan ?"
    mom "Sudah mendingan"
    mc "Ngomong-ngomong ayah kemana ? Lembur lagi ?"
    mom "Iyaa hari ini juga lembur kerjanya"
    mom "Soal ada Projek dari kantornya"
    mc "Hmmm.. Begitu"
    mom "Tumben [mg2_Last] ga kerumah ?"
    mc "...."
    mc "tadi anterin temannya rumahnya jauh juga"
    mom "Hmmm.. Begitu. agak sepi juga disini"
    mom "Ada anak itu jadi heboh hahahha"
    mc "...."
    mom "Oiya,, Nanti setelah selesai biar ibu aja yang beres-beres"
    mc "Ga usah biar aku saja"
    mom "Hmm.. iyadah Ibu Tidur saja kalau gitu"
    "~Makan Malam~"
    mc "Kenyangg sekali"
    mom "Ibu ke kamar dulu ya"
    mc "Okie, Biar aku yang beresin semuanya"

    scene kamar malam
    mc "Haa.. Leganya. enaknya ngapain ya ?"
    cat "Meooww"
    mc "Eh ada [cat] sini sini tidur bareng aku"
    mc "Tidur aja kalau gitu benarkan [cat]"
    cat "Nnnyaaa"

    jump day3_Kirana

label day2_Miselia:

    scene ruang keluarga
    mom "Nak, ayo makan"
    mc "iya bu sebentar, aku ambil tas dulu"
    mc "Bu, bapak sekarang apa udah sampe jogja ?"
    mc "Oalah, okedeh semoga urusan bapak lancar"
    mom "Nak, bagaimana dengan sekolahmu? apakah kamu senang dan nyaman?"
    mc "I..iyaaa.. lumayan bu, alhamdulillah aku nyaman kok buk, kenapa memang? apa wajhku keliatan  gelisah?"
    mom "Oalah syukurlah kalo baik baik saja kamu nak, tidaak.. anak ibu tetap yang terbaik dimata ibu, anak yang sederhana dan kuat"
    mc "Alaaahh ibu mah bisa aja , tidakk buu, aku hanya manusia biasa, ibukkk.. tenang aja yaa, mc udah bisa pulih dari masalalu mc , semogaa rasa takut ini segera berakhir bu dengan berjlannya waktu"
    mom "Iya nak , cerita sama ibu ya , kalo ada apa apoa , jangan cuman diam dan di pendem sendiri ya"
    mc "Iya buu, kalo begitu aku pamit berangkat ke sekolah dulu ya, assalamualaikum"
    mom "Waalaikumsalam, hati hati di jalan ya nak , semangat belajarnya"

    scene angkot

    sa "Naakk, ayo masuk , duduk di depan aja "
    mc "Wahhh,, iya pak , okee dehh"
    sa "Nak, hari ini bapak baru dapet penumpng baru 2 , kamu dan 1 ibu tadi udah turun di pasar gebang"
    mc "Loh pak, kok tumben sepi ya, pada kemana orang orang ini?"
    sa "Ya itu , bapak juga ndak tau, mungkin garagara baru bermunculan itu lo nak , aplikasi apa itu ya namanya yang warna ijo, baoak ndak tau kudet hehehe"
    mc "Hmm, ya namanya rejekipak , datangnya ndak di sangka sangka, insha allah habis ini rame kok pak, aamiin"
    sa "Wah sudah sampai nak , yasudah silahkan belajar , yang semangat semoga sukses biar ndak ajdi kayak bapak hehehe"
    mc "Waduh pak ,bapak juga sukses , terimakasih pak , aku masuk kedalam dulu ya , bapak hati hat di jalan, semoga makin banyak penumpang ya "

    scene lorong
    $ mt = "Meta"
    $ hsn ="Husni"
    mg1 "MC.. mc... "
    mc "Kamu memanggilku?"
    mg1 "Iyalah, yakali aku manggil pak kebon dengan namamu"
    mc "Iya iya, ada apa emangnya ?"
    mg1 "Enggak, gapapa , aku cuman mau manggil aja"
    mt "Waduhh bagaimana ini broo, aku gatauu soal no 2. apa kamu bisa"
    hsn "Huu, kamu aja ndak tau, apalagi aku"
    mg1 "Eh kaliann pada ngapain sih?"
    mt "Ini lo sel, kamu sudah selesai belum?"
    mg1 "Hah.. pr ? waduh aku lupa juga , ehhh kamu udah selesai belum?"
    mt "Ehh,,, mc kamu kan ganteng , baik, dan pinter hehehe, boleh dong kalo kita kita pinjem buku pr mu "
    mc "Coba kerjakan sendiri dulu , nanti yang ga bsa ,tanyakan aku"
    mt "Huu, dasar pelit , sok banget sih, orang kita kita juga cuman sekali mintanya kok dasarrr pamtes banyak yang suka ke kamu"
    mg1 "Eh, mettt kok kamu jadi nyolot si ke mc, mc kan bukannya gamau ngasih tau jawabannya , cuman dia bilang kalo yang gabisa baru tanaykan kan"
    mc "Udah udahh,, gausah ribut. bentar aku kasih bukunya ."
    mt "Heheh makasih ya , maapin aku kalo omonganku kasar tadi"
    mc "iya sama sama "
    sr "Selamat pagi anak anak, bagaimana kabar hari ini?"
    sk "Pagi buu" 
    sr "Oiyaaaa, hari ini ibu ingat kalo ada tugas rumah , yang ibu berikan 2 hari yang lalu ya ?"
    sr "Oke deh, sekarang silhkan di tukar dengan teman seelahnya , untuk di koreksi"
    sk "Baik bu"
    sr "Kalau sudah di bagikan , nanti ibu tunjuk 1 per 1 untuk maju kedepan dan mengerjakan soal yang telah ibu berikan"
    hsn "Waduhh gawat nih , kalo sampek aku yang ketunjuk"
    sr "Mc.. silahkan kamu maju kedepan dan kerjakan soal no 1"
    mc "Baik Bu"
    mt "Huuhh untungnya bukan kita mat yang di panggil"
    hsn "Iya met, untung"
    mg1 "Ayo ke kantin"
    mc "Iya sebentar, aku beresin ini dulu "

    scene kantin
    mg1 "Hey mc kamu kok hebat bgt gmn si kok bisa dpt nilai tertinggi ?"
    mc "Kuncinya hanya satu yaitu raji belajar ,udah itu aja"
    mg1 "Hummmm begitu ,boleh gak aku belajar bareng sama kamu"
    mc "Hmm iyadeh tapi nanti aku kabarin ya bisanya kapan hehe"

    "Kuis kuis "
    mg1 "Kamu pulang bareng siapa ? "
    mc " Sendiri jalan kaki , kenapa sel?"
    mg1 "Yauda bareng aku aja gapapa ayo"
    mc " Ok deh makasi ya"

    scene jalan
    mg1 "Kok tumben kamu naik angkot tadi berangkatnya ?"
    mc "Iya , bapak ku lagi pergi dan motornya di bawa"
    mg1 "Oalah"

    scene rumah
    mc "Udah sampai , makasih ya udah mau nebengin, aku masuk dulu, kamu hati - hati ya"
    mg1 "Oke sama sama , assalamualaikum"
    mc "Waalaikumsalam"

    jump day3_Miselia

label day2_Airin: