label day3_Kirana:
    scene bg jendela kamar terlihat burung
    "Sudah Pagi Ternyata, sebaiknya aku bergegas menuju sekolah"

    scene dapur
    mom "Ehh.. Sudah Mandi Ternyata"
    mc "Hehhe Iya"
    mc "[dad] kemana bu ?"
    mom "[dad]mu berangkat pagi tadi. ibu sudah siapin bekal untuk ayahmu tadi"
    mc "Kalau gitu aku makan dulu ya bu"
    mom "Iyaa nak"
    "Kami pun Makan bersama walaupun [dad] sudah berangkat duluan"
    mc "Kalau gitu aku ambil tas dulu di kamar"
    mom "Oiya,, Uang Sangumu sama Bekal ada di meja makan!!"
    mc "Dimana bu ?"
    mom "Ini di Meja"
    mc "Iya bu, kalau gitu aku berangkat"

    scene gerbang sekolah
    "Tumben ga ada yang manggil untuk bareng ke kelas. Apa Aku kepagian ya berangkatnya ? "
    "Tapi hari ini enak banget sunyi sekali pas masuk ke sekolah"
    
    scene kelas 
    "Ternyata yang baru datang hanya beberapa saja sepertinya emang kepagian"
    "Mungkin kalau gitu sebaiknya aku tidur dulu"
    "~Beberapa Menit Kemudian~"
    "~Ding Dong~"
    mg2 "Hee Bangun.. "
    mc "Umm.."
    mg2 "Sudah mau mulai jam pelajarannya.. Bangunn.."
    mc "Ahh.. sudah masuk ternyata"
    mg2 "Iyaa.. sana raup dulu"
    mc "Oh Ok kalau gitu aku raup dulu"

    scene depan kelas 
    sr "Loh [mcFirst] mau kemana ?"
    mc "Mau ke kamar mandi bu"
    sr "Ealah, Iyaa dah sana"
    mc "Baik bu !!"

    scene kelas
    sr "Selamat sore anak- anak"
    kk "Loh, ini masih pagi loh bu.. kok selamat sore sih"
    sk "hahhahahhahahahhaha"
    sr "Alhamdulillah brati masih semangat ya, otak nya masih fresh. baik lah langsung saja, ibu mulai, selamat pagi semuanya"
    sk "Pagi bu"
    sr "Kalau gitu kita mulai pelajarannya"
    mc "Permisi bu"
    sr "Iya Iyaa silahkan duduk"
    "~Materi Fungi lanjutan~"
    "~Ding Dong~"
    na "Brader ikut ke kantin ga ?"
    mc "Ohh Okk"
    mg2 "Aku ga diajak nih ?"
    mc "Kan ada [ol]"
    ol "[mg2_Last] Ayoo Ke Kantin"
    mc "Tuhkan diajak sama [ol] Ntar ketemuan disana aja"
    mc "Kalau gitu aku duluan ke kantin"

    scene kantin
    na "Carikan tempat duduk kosong dong ntar aku aja yang mesenin"
    na "Mau pesen apa ?"
    mc "Mungkin Bakso aja kali ya"
    na "Okk dahh, Beli berapa baksonya ?"
    mc "5000an aja dah cukup"
    mc "Kalau gitu aku cari bangku yang kosong dulu"
    "Mungkin sebaiknya duduk disini"
    mg2 "Hooo Ternyata ada disini kamu"
    ol "Kami Numpang duduk disini juga ya"
    mc "Oh Okk"
    ol "Btw, Makananmu mana ?"
    mc "Tuh lagi dibawain sama si [na]"
    na "Loh Loh ada [mg2_Last] sama [ol] ternyata"
    mg2 "Ya kan ketemuan di kantin"
    ol "Iyaa nih"
    mc "dah dah ayo makan setelah itu balik ke kelas"
    mc "kalian makan apa ?"
    ol "Aku beli mie ayam"
    mg2 "Kalau aku Nasi Pecel. Kalau kalian bagaimana ? "
    mc "Aku makan Bakso"
    na "Kalau aku pesen Nasi Goreng sih hahah"
    mc "Dah ah Mari Kita Makan"

    scene kelas
    mg2 "Fuuu.. Kenyangnya~"
    ol "Pesenmu banyak kali tadi Nasi Pecelnya Jumbo"
    mg2 "Hehehehe"
    "~Ding Dong~"
    ol "Aku kembali ke bangku ku dulu ya"
    mg2 "Okie"
    sr "Selamat malam anak-anak"
    sk "Lah.. tadi pagi selamat sore sekarang siang selamat malam"
    sk "Ihh Bu Senda ini"
    sr "Heheheh Becanda. Ternyata Kalian masih semangat ya"
    sr "Tumben, Biasanya siang-siang gini dah lesu"
    sk "Itu mah perasaannya Bu Senda aja kali hehehe"
    sr "Dasar kalian yaa"
    sk "hahahahha.. Ampun Bu ampun haha"
    sr "Sudah Sudah mari kita mulai saja ya"
    sr "Oiyaa, Seperti kemarin berkelompok lagi ya terus ibu mau rapat lagi kemungkinan sebentar lagi pulang"
    sr "Sekelompok 4 orang sekelas ini ada 35 orang"
    sr "Sisanya bisa bikin kelompok sendiri bisa bergabung sama temannya"
    sr "Tentuin sendiri kelompoknya ya"
    "Hmm... Kelompok lagi kelompok lagi. sepertinya aku ga menemukan kelompok"
    mg2 "Mau kelompokan sama aku ?"
    mc "Bukannya sudah cukup ?"
    mg2 "tapi kan sisanya boleh bergabung ke kelompok mana pun"
    mc "Kelompokmu ada siapa aja ?"
    $ nd = "Nindi"
    $ ad = "Ardi"
    mg2 "Ada [nd], aku, [ol], [ad]"
    mc "Aku aja nih lakinya ? Kalau kelompoknya [na] ada siapa aja ?"
    mg2 "Kayaknya sudah 5"
    mc "...."
    mc "Yaudah lah aku masuk kelompokmu aja"
    mg2 "Okie"
    sr "Apa Semua sudah dapat kelompok ?"
    sr "Kalau gitu ini tugasnya"
    "~Ding Dong~"
    sr "Ternyata sudah bel pulang, kalau gitu ibu akhiri saja untuk hari ini"
    sr "Oiya, Jangan lupa dikerjakan ya"
    sk "Baik Buu"
    sr "Kalau gitu Ibu ke ruang guru dulu"
    sk "Iyaa bu"
    nd "Mau kerumahnya siapa ? Kerja kelompoknya"
    mg2 "Dirumahku atau [ol] ? Rumahmu juga gapapa sih"
    nd "Kalau dirumahnya [mcFirst] Bagaimana ?"
    ol "Boleh juga itu"
    mc "...."
    mc "Jangan dirumahku soalnya semuanya pada keluar jadi rumahku dikunci"
    nd "Kamu ga dititpin kunci ?"
    mc "Ga soalnya setiap pulang sekolah sudah ada dirumah"
    mc "Berhubung sekarang pulang lebih awal jadi dirumahku ga ada siapa-siapa"
    mc "Saranku dirumahnya kalian aja"
    mg2 "Kalau gitu rumahmu aja Nin gimana ?"
    ol "Bagaimana kalau Kerja kelompok di taman kota ?"
    mg2 "Boleh juga itu"
    nd "Yaudah kalau gitu di taman kota aja"
    mc "Aku ngikut aja"
    ad "Aku sih ok ok aja"

    scene gerbang
    nd "sudah rede semua ini kan ?"
    ad "Tinggal Berangkat aku"
    $ mgol = "Ardana dan Filo"
    mgol "Gass dah rede nih"
    nd "Kalau gitu Joss berangkat kita"

    scene alun-alun
    ol "Yeayy Sudah sampai"
    nd "Kita kerjain langsung apa pesan sesuatu dulu ?"
    ad "Pesan dulu aja dong di FoodCourtnya sekalian kerjain disana"
    mc "Aku ngikut aja"
    mg2 "Yauda, Pesan aja dulu sambil nunggu camilan ama minumannya datang kita kerjain aja"

    scene foodcourt
    ol "Kalian mau pesan apa gaes ?"
    nd "Aku minumnya pesan Es Jeruk aja"
    mg2 "Aku pesan jus jambu aja"
    ad "Aku pesan Es Jeruk juga"
    mc "Milkshake Vanilla"
    ol "Kalau gitu Es Jeruk 2, Jus Jambu 1, Milkshake Vanilla 1"
    ol "Kalau camilannya pesen apa ini ? yang sekiranya bisa dibuat makan bersama"
    nd "Kalau gitu Kentang Goreng 2 terus Pisang coklat 1"
    mg2 "Nugget jugaa 2 sama tempe goreng 2"
    ol "Okk dah kalau gitu aku pesanin dulu ya"
    ad "Ehh.. tunggu dulu tambah itu juga Tahu Crispy 1"
    ol "Okie Doki"
    mc "Jadi, berhubung nunnggu pesanan datang kita kerjakan dulu soal dari Bu Senda"
    nd "Boleh"
    mg2 "Yok,, Keluarkan Tugasnya biar cepat selesai"
    ad "Gass Keun"
    "~Tugas Soal~"
    "Kemudian makanannya datang, tugasnya pun sudah selesai juga dan aku makan bersama teman kelas"
    "Aku pikir ini tidak begitu buruk"
    ol "Capeknya ngerjakan tugasnya. Mari kita makan"
    ad "Ngomong-ngomong aku pernah kelihatan kamu dulu waktu SMP"
    ad "Kalau ga salah kamu sering dibully dulu ya"
    ad "Sampe ada kasusnya"
    mc "...."
    mc "Aku ? Kayaknya salah orang"
    nd "Dibully gimna ?"
    ad "Soalnya dulu ada yang terbully habis habisan itu seingatku"
    ol "Kejamnya, kok masih suka bully Terus gimana kabar anak itu ?"
    ad "Ntahlah, aku ga tau juga dah lupa soalnya hahahha"
    mg2 "Kok jadi tegang gini suasananya ?"
    ol "Bahas yang seru aja lah"
    ol "Jadi Mencekam gini suasanya kyk dirumah horror aja"
    mc "Hahahaha... Ntr kalau [ol] pulang pas malamnya di kamar hati-hati"
    ol "Dihh.. Malah Nakutin ada apa emangnya"
    mc "[mg2_Last] numpang boker lewat jendela kamarmu"
    mg2 "Dihh.. Dasar kamu minta dipukul yaa"
    mc "Heheh maaf maaf"
    ad "Hahahaha ada-ada aja"
    "Meskipun suasananya sempat tegang, tidak buruk juga hal ini ternyata"
    scene foudcourt sore
    mg2 "Sudah sore nih, Kuy Pulang"
    mc "Ahh Ok ok"
    mg2 "Kalian ga mau pulang gaes ?"
    ad "Iyaa ini aku juga mau pulang malam ini ada janjian soalnya"
    mg2 "[nd] dan [ol] ga pulang juga ?"
    $ ndol = "Nindi dan Filo"
    ndol "Yaa pulang lah, yakali mau ngesatpam disini"
    ad "Pfftt"
    ad "gapapa nambah satpam disini hahha"
    ndol "Mending kamu aja deh jadi satpam disini"
    ad "Tuh kalian berdua serasi cocok jadi satpam sini daripada aku"
    ol "dah ah Pulang aja kalau gini ga pulang - pulang"
    mg2 "Kalau gitu aku duluan"
    $ mm2 = "[mcFirst] dan [mg2_Last]"
    $ all = "[ad], [nd], dan [ol]"
    mm2 "Aku duluan gaes.. Bye Byee"
    all "Okie.. Baibai hati-hati dijalan semuanya"

    scene depan tumah sore hari 
    mc "Terima kasih [mg2_Last]"
    mg2 "Gapapa no problem, aku pulang duluan titip salam ke tante"
    mc "Okk"

    scene ruang tamu
    mc "Aku Pulang!!"
    mom "Iyaa !!"

    scene ruang keluarga
    mc "Ada salam dari [mg2_Last] barusan"
    mom "Loh ga mampir ?"
    mc "Keburu Malam katanya terus sudah capek juga"
    mc "Kalau gitu aku langsung tidur bu"
    mom "Ahh iya iyaa"
    mc "[cat] sudah dikasih makan ?"
    mom "Sudah tadi, terus nonton film sama Ibu disini sampai kamu datang hahah"
    mc "[cat] mau ikut tidur ?"
    cat "Meoooww"

    scene kamar 
    "Salin Baju dulu lah terus tidur, capek bener"
    "Leganya enaknya kasur ini buat rebahan"
    mc "Kuy tidur disini [cat] soalnya kamu hangat hahaha"
    cat "Fuurrr Fuurrr"
    mc "Lahh cepet banget pasti kecapekan nonton tv hahahha"


label day3_Miselia:

label day3_Airin: