label day7_Kirana:

    scene kamar
    "Haa.. kemarin benar benar heboh tak kusangka bisa sampai segitunya"
    "Grup di Hp pun ramai masih membahas jalan-jalan ke pantai"
    "Hmmm.. Anak-anak ternyata masih belum tau kejadian kemarin"
    "Padhal mereka tinggal bilang ke lainnya"
    "~Suara Telpon~"
    "Haaa... ngapain si Nada Nelpon"
    na "Halo lur"
    mc "Ada apa ?"
    na "Kamu ga jadi ikut ?"
    mc "Ga, kenapa lur ?"
    na "Pasti gara-gara tadi malam"
    mc "Ternyata sudah diceritain ya ?"
    na "Iyaa, sama si [kk]"
    na "yahh,, itu emang tidak sepenuhnya salahmu"
    na "Aku kalau jadi kamu pasti marah juga lah tiba-tiba ungkit masa kelam hahahha"
    mc "Apa aku harus ikut ?"
    na "Ikut saja, kalau ada masalah tenang brader ada aku hahaha"
    mc "Hadeh... okk lah"
    mc "Berangkat kapan ini ?"
    na "Sebentar lagi brader"
    mc "Okk kumpul dimana ntar ?"
    na "Di alun alun"
    mc "Okk"

    scene kamar mandi

    scene dapur
    mom "Kamu mau kemana ?"
    mc "Berangkat jalan-jalan"
    mom "Kamu gapapa ?"
    mc "Gapapa bu, cuma kemarin terjadi yaa agak gimana gitu ?"
    dad "Cerita aja gapapa"
    dad "[ai] selalu mendengarkanmu"
    mc "Sigh.. Jadi kemarin setelah dari mall pergi ke cafenya"
    mc "Tiba-tiba [mg2_Last] tanya tentangku dulu"
    mc "Aku sudah ga mau ngulik masa lalu malah dibahas sama dia jadi aku emosi terus aku pulang pesen kojek"
    ai "Hoo.. Jadi begitu"
    mom "Kamu memang ga salah, [mom] selalu mendukungmu tapi mg2_Last tidak sepenuhnya salah mungkim ada alasannya"
    dad "Terus gimana itu si [mg2_Last]"
    mc "Ntahlah, aku ga tau"
    mom "Sudah-sudah nanti makin badmood loh pagi-pagi masa anak ibu sudah badmood padahal kamu sudah kembali jadi ceria"
    mc "hahah Iya bu"
    dad "Kalau gitu kita makan aja"
    mc "Okie Selamat makan"

    scene depan rumah
    dad "Hadapi saja terobos.. Anak Ayah kuat sudah lebih baik daripada yang dulu"
    mom "Abaikan saja klo ada yang mengganggumu"
    mc "Terima kasih yah bu, kalau gitu aku berangkat"
    ai "Iyaa hati-hati nak"

    scene alun-alun
    na "Oeee oeee [mcFirst]"
    mg2 "...."
    kk "Sudahlah, [mg2_Last]"
    mc "Ini aku yang terakhir apa gimana ?"
    na "Ga, nunggu [skce1] dan [ol]"
    mc "Ah..okk"
    wkk "Kalau gitu kita tunggu di FoodCourt aja kuy"
    skco2 "Gass kan"
    kk "Eii.. bilang dulu ke [skce1] dan [ol] nanti kita ke FoodCourt mereka nyariin"
    wkk "Ehh,,, Iyaa yaa ahhaha"
    wkk "Oiyaa,, [mg2_Last] kabarin [ol] aku kabarin si [skce1]"
    mg2 "Iyaa ya kukabarin"
    mc "....."

    scene foodcourt
    kk "Kalian pesan apa ?"
    na "Aku Jus mangga aja"
    mc "Aku Es Jeruk"
    wkk "Milkshake Oreo"
    skco2 "Es Coklat"
    kk "Okk.. Kalau kamu na ?"
    mg2 "Terserah dah"
    kk "Okk random yaa"
    mg2 "Jus Jambu aja dah"
    na "Sekalian pesan Snack Kentang goreng sama Tempe Goreng"
    na "Nunggu mereka pasti lama jadi sekalian nyamil lah"
    wkk "Benar juga"
    skco2 "Beli 3 Kentang gitu 2 Tempe kayaknya cukup"
    kk "Hai hai klo gitu aku mesan dulu"
    wkk "Sudah siap kamera belum ?"
    mg2 "Sudah dong"
    skco2 "Mantap!!"
    kk "Aku sudah pesan tinggal tunggu aja"
    kk "omonng-omong gimana mereka berdua ?"
    mg2 "[ol] baru bangun tapi sebentar lagi berangkat"
    wkk "Kalau [skce1] sudah OTW"
    kk "Okk dah kalau gitu"
    $ ifc = "Ibu-Ibu FoodCourt"
    ifc "ini Pesenannya"
    kk "Terima Kasih bu"
    na "Skuy Libas hahaha"
    na "[mcFirst] Kentangnya bro dimakan jangan lupa"
    mc "Okk"
    "~Kami pun menikmati pesanan kami sambil menunggu teman kami~"
    "~Tak Lama kemudian [ol] dan [skce1] datang~"
    ol "Maaf, aku kebablas tidurnya heheh tadi malam habis nonton Drakor"
    mg2 "Ihh.. Kamu nih"
    ol "hehehe"
    skce1 "Aku tadi masih bantu bantuin ibu"
    skco2 "Kitaa Gass ga ini apa kalian mau pesan dulu ?"
    ol "Langsung gas aja aku juga sudah makan"
    skce1 "Aku juga sudah makan"
    na "Kalau gitu gass kita berangkat"
    wkk "Let's Goo"

    scene pantai
    ol "Yeay,, Akhirnya sampai juga"
    wkk "Mantap emang"

label day7_Miselia:

    scene kamar
    mc "Astaghfirullah, sekarang hari senin kah? aku lupa kalo sekarang sekolah"
    mom "Nak, kamu ini sekarang hari senin loh, kamu kok bangunnya siang, apa ga ikut upcara?"
    mc "Aku lupa buk, ku kira sekarang hari minggu , ternyata senin"
    mom "Yasudah segera mandi , ibu siapkan sarapan dulu"
    mc "Iya bukk , aku mandi dulu"

    scene ruang keluarga
    mom "Nak , kali ini ibu tidak masak daging, karena sekarang harga daging melunjak pesat di pasar , mahal banget, makan sama telur aja ya"
    mc "Iyabu, tidakmasalah, yang penting yang masak tu ibu, hehhe"
    mom "Ah kamu ini , sana cepat sarapan, keburu telat nanti"
    mc "Bu aku berangkat sekolah dulu ya , minta doanya semoga hari ini di beri kelancaran dan kemudahan untuk belajar"
    mom "ya nak , ibu selalu mendoakan kamu , supaya jadi orang yang sukses berguna bagi keluarga, nusa dan bangsa"
    mc "Yauda bu , makasi ya , assalamualaikum"

    scene jalan
    mc "Ya Allah, aku sebenernya pengen banget punya sepeda motor, biar bisa brangkat sekolah, ga harus naik angkot ataupun jalan kaki seperti ini"
    kk "Heii , dasar miskin sekolah kok jalan kaki hahha ini udah jaman SMA bre gamalu apa hahha"
    mc "Astaghfirullah haladzim"

    scene lorong kelas 
    $ mln = "Melin"
    mln "Astaga , maaf ya aku ga sengaja"
    mc "Duhh..iyaaa gapapa deh kalo kamu ga sengaja "
    mln "Ya ampun liat baju kamu jadi kotor, sebentar aku ambilin tissue ya"
    mln "Maaf ya kak, aku ga sengaja maaf bnget ya"
    mc "Iya gapapa kok, biar aku bersihin aja ke kamar mandi"
    mln "Btw kamu kelas apa ? kok aku jarang liat kamu ya "
    mc "Aku anak  X MIA  2 , kamu kelas brapa ?"
    mln "Aku melin X IIS 3"
    mg1 "Heh, mgapain kamu di sini ?"
    mc "Ini , tadi melin ga sengaja numpahin minuman ke bajuku "
    mg1 "Hah, ehh kamu kalo jalan pake mata dong , ga liat apa kalo di depan ada orang"
    mln "Maaf kak, aku sudah minta maaf tadi ke dia, dan udah ku beri tissue untuk di bersihkan, tapi dia malah mau ke kamar mandi aja"
    mc "Udah stop, gapapa aku sel, udahhh sekarang mending kita jalan ke kelas aja ayo"
    mln "Sekali lagi aku minta maaf ya mc"
    
    scene depan kelas 
    mc "Misel, tolong taruh kan tas ku dulu ya, aku mau ke toilet dulu untuk membersihkan baju ku ini "
    mg1 "Iya deh,sana buruan "

    scene toilet
    $ dn = "Dani"
    $ ags = "Agus"
    dn "Adudu ada adekelas yang sok tampan ini gengs, enaknya kita apain ya?"
    ags "Hahaha, ganteng ganteng tapi cupu , lu cowo apa cewe nih"
    ags "Eh eh liat liat, mana bajunya udah buluk, eh kena air comberan kali ye hahha"
    mc "Permisi kak , saya mau lewat "
    dn "Sono gih, dasar gembel"
    mc "Ya allah, kenapa ya aku selalu jadi rendahan orang lain, padahal aku gapernah nyari masalah selama ini"

    jump day8_Miselia

label day7_Airin: