label day7_Kirana:

    scene kamar
    "Haa.. kemarin benar benar heboh tak kusangka bisa sampai segitunya"
    "Grup di Hp pun ramai masih membahas jalan-jalan ke pantai"
    "Hmmm.. Anak-anak ternyata masih belum tau kejadian kemarin"
    "Padhal mereka tinggal bilang ke lainnya"
    "~Suara Telpon~"
    "Haaa... ngapain si Nada Nelpon"
    na "Halo lur"
    mc "Ada apa ?"
    na "Kamu ga jadi ikut ?"
    mc "Ga, kenapa lur ?"
    na "Pasti gara-gara tadi malam"
    mc "Ternyata sudah diceritain ya ?"
    na "Iyaa, sama si [kk]"
    na "yahh,, itu emang tidak sepenuhnya salahmu"
    na "Aku kalau jadi kamu pasti marah juga lah tiba-tiba ungkit masa kelam hahahha"
    mc "Apa aku harus ikut ?"
    na "Ikut saja, kalau ada masalah tenang brader ada aku hahaha"
    mc "Hadeh... okk lah"
    mc "Berangkat kapan ini ?"
    na "Sebentar lagi brader"
    mc "Okk kumpul dimana ntar ?"
    na "Di alun alun"
    mc "Okk"

    scene kamar mandi

    scene dapur
    mom "Kamu mau kemana ?"
    mc "Berangkat jalan-jalan"
    mom "Kamu gapapa ?"
    mc "Gapapa bu, cuma kemarin terjadi yaa agak gimana gitu ?"
    dad "Cerita aja gapapa"
    dad "[ai] selalu mendengarkanmu"
    mc "Sigh.. Jadi kemarin setelah dari mall pergi ke cafenya"
    mc "Tiba-tiba [mg2_Last] tanya tentangku dulu"
    mc "Aku sudah ga mau ngulik masa lalu malah dibahas sama dia jadi aku emosi terus aku pulang pesen kojek"
    ai "Hoo.. Jadi begitu"
    mom "Kamu memang ga salah, [mom] selalu mendukungmu tapi mg2_Last tidak sepenuhnya salah mungkim ada alasannya"
    dad "Terus gimana itu si [mg2_Last]"
    mc "Ntahlah, aku ga tau"
    mom "Sudah-sudah nanti makin badmood loh pagi-pagi masa anak ibu sudah badmood padahal kamu sudah kembali jadi ceria"
    mc "hahah Iya bu"
    dad "Kalau gitu kita makan aja"
    mc "Okie Selamat makan"

    scene depan rumah
    dad "Hadapi saja terobos.. Anak Ayah kuat sudah lebih baik daripada yang dulu"
    mom "Abaikan saja klo ada yang mengganggumu"
    mc "Terima kasih yah bu, kalau gitu aku berangkat"
    ai "Iyaa hati-hati nak"

    scene alun-alun
    na "Oeee oeee [mcFirst]"
    mg2 "...."
    kk "Sudahlah, [mg2_Last]"
    mc "Ini aku yang terakhir apa gimana ?"
    na "Ga, nunggu [skce1] dan [ol]"
    mc "Ah..okk"
    wkk "Kalau gitu kita tunggu di FoodCourt aja kuy"
    skco2 "Gass kan"
    kk "Eii.. bilang dulu ke [skce1] dan [ol] nanti kita ke FoodCourt mereka nyariin"
    wkk "Ehh,,, Iyaa yaa ahhaha"
    wkk "Oiyaa,, [mg2_Last] kabarin [ol] aku kabarin si [skce1]"
    mg2 "Iyaa ya kukabarin"
    mc "....."

    scene foodcourt
    kk "Kalian pesan apa ?"
    na "Aku Jus mangga aja"
    mc "Aku Es Jeruk"
    wkk "Milkshake Oreo"
    skco2 "Es Coklat"
    kk "Okk.. Kalau kamu na ?"
    mg2 "Terserah dah"
    kk "Okk random yaa"
    mg2 "Jus Jambu aja dah"
    na "Sekalian pesan Snack Kentang goreng sama Tempe Goreng"
    na "Nunggu mereka pasti lama jadi sekalian nyamil lah"
    wkk "Benar juga"
    skco2 "Beli 3 Kentang gitu 2 Tempe kayaknya cukup"
    kk "Hai hai klo gitu aku mesan dulu"
    wkk "Sudah siap kamera belum ?"
    mg2 "Sudah dong"
    skco2 "Mantap!!"
    kk "Aku sudah pesan tinggal tunggu aja"
    kk "omonng-omong gimana mereka berdua ?"
    mg2 "[ol] baru bangun tapi sebentar lagi berangkat"
    wkk "Kalau [skce1] sudah OTW"
    kk "Okk dah kalau gitu"
    $ ifc = "Ibu-Ibu FoodCourt"
    ifc "ini Pesenannya"
    kk "Terima Kasih bu"
    na "Skuy Libas hahaha"
    na "[mcFirst] Kentangnya bro dimakan jangan lupa"
    mc "Okk"
    "~Kami pun menikmati pesanan kami sambil menunggu teman kami~"
    "~Tak Lama kemudian [ol] dan [skce1] datang~"
    ol "Maaf, aku kebablas tidurnya heheh tadi malam habis nonton Drakor"
    mg2 "Ihh.. Kamu nih"
    ol "hehehe"
    skce1 "Aku tadi masih bantu bantuin ibu"
    skco2 "Kitaa Gass ga ini apa kalian mau pesan dulu ?"
    ol "Langsung gas aja aku juga sudah makan"
    skce1 "Aku juga sudah makan"
    na "Kalau gitu gass kita berangkat"
    wkk "Let's Goo"

    scene parkir
    ol "Yeay,, Akhirnya sampai juga"
    wkk "Mantap emang"

    scene pantai
    bl "Segarnya aroma pantai ini"
    bl "Kita foto dulu atau gimana ?"
    na "Ganti baju dulu lahh, tapi klo mau foto duluan sih gapapa"
    bl "Mending kita foto duluan saja jadi ada Awal datang sama akhir"
    skce1 "Boleh itu gass keun"
    skco2 "Cari tempat dulu kuy yang cocok buat foto"
    kk "Sini kayaknya cocok cepat sini sini"
    kk "Aku ga sabar mau basah-basahan hahahah"
    bl "Sudah siap kan ?"
    na "Sudah lah"
    play sound ambil_foto
    mg2 "Okk dah kalau gitu skuy ganti baju.. main basah-basahan kita"
    bl "Yuukk!!"
    skce1 "Tunggu akuu!!"
    ol "Aku juga mau ikut oee"
    wkk "[kk] kamu ga ikut mereka ganti baju ?"
    kk "Aku pake baju ini aja sudah aman kok"
    na "Wihhh.. Segarnya airnya kuy renang [mcFirst]"
    mc "Okk wait buka baju"
    mc "Gass"
    skco2 "Aku juga ikutan oee"
    kk "Kamu ga ikut renang ama mereka ?"
    wkk "Bentar lagi, kita bahas dulu cara dekatin mereka berdua lagi"
    kk "Kamu tauu ?"
    wkk "HAhahah,, kelihatan dari wajah mereka berdua"
    kk "Iyaa juga sih lebih canggung sekarang"
    kk "gimana kalau aku saja yang jaga barang-barang kita"
    kk "Nanti gantian aku mau renang juga lah, nanti kan si [mg2_Last] main-main juga kan"
    kk "Kalau bisa kamu dekatin jadi misal mereka berdua dekat kalian ajak yang lainnya pergi"
    wkk "Boleh juga idenya bisaa nihh dicobaa"
    wkk "yaudah aku kesana dulu mau bilang ke anak-anak suruh ikut aku misal [mg2_Last] sudah datang"
    wkk "Yuhuuuu.. Sea I'm coming"
    na "Hahah segar kan"
    kk "Enaknya lihat mereka"
    mg2 "[kk] kamu ga renang ?"
    kk "Aku jaga barang-barang dulu"
    kk "Sana dah kalau mau renang nanti gantian yang jaga hehehe"
    mg2 "Kenapa, ga kita berdua saja yang jaga ?"
    kk "Aku aja cukup sana main dulu sambil dinginkan kepalamu itu"
    mg2 "Okie [kk]"
    ol "Kami duluann [kk]"
    kk "Iyaa"

    scene air pantai
    wkk "Kuy kuy ntr lagi ikut aku, explore kita"
    skco2 "Gasskeun"
    mg2 "Mainn duluan nih bocah hahahha"
    na "Sini kau"
    "~cepyar~"
    mg2 "Awas kau nada"
    na "Pfft,, serbu para ciwi-ciwi gaes"
    skco2 "Lets goo"
    wkk "Kuyy kitaa kaburr pergii"
    mc "Lahh ?"
    mg2 "...."
    mc "...."
    ol "yang lain mana ?"
    mg2 "Kabur mereka"
    bl "hohoho sisa 1 disini,, serbuu!!!"
    ol "Gogogogogo"
    mc "Eh eh kok jadi aku"
    mc "Gyahhh.. Blurp~ Blurp~"
    $ all_girls = "[ol], [mg2_Last], [skce1], dan [bl]"
    all_girls "HAhahhahaha"

    scene pantai
    kk "Kayaknya berjalan lancarr.."
    wkk "yoo"
    kk "Astaga, kaget aku"
    wkk "Gimana ?"
    kk "Kelihatannya lancar sih"
    wkk "Hahah benar kan syukurlah kalau mendingan"

    scene air pantai
    "Aku rasa hari fokus bersenang-senang saja lah meskipun ada beberapa problem sama [mg2_Last]"
    "Ga begitu buruk juga, jadi gini rasanya ada teman yang ngesupport juga"
    "Kami pun bergantian yang menjaga barang, bermain di pantai hingga sore pun menyenangkan"

    scene pantai sore
    bl "Kuy foto lagi, foto kenangan diakhir mengunjungi pantai"
    kk "Gas gas berangkat"
    wkk "[ol]... [ol].... ppstt nanti pulang sama yang lainnya aja"
    ol "ehh,, Kenapa ?"
    wkk "Gapapa,, biar [mcFirst] sama {mg2_Last}"
    ol "Iya deh, yang penting pulang hahaha"
    bl "Kalian ini ngomong mulu ga siap-siap"
    wkk "hehehh maaf-maaf"
    bl "1... 2... 3..."
    skce1 "Cepat sini lari lari"
    play sound ambil_foto
    na "Yokk,, pulang yok pulang"

    scene parkir
    wkk "[mg2_Last] pulangmu bareng [mcFirst]"
    mg2 "Lah,, kenapa ?"
    mc "...."
    wkk "Soalnya aku langsung pulang beda arah juga kan"
    mg2 "hnnggh.. iya dehh"
    wkk "[mcFirst] kamu ga amasalh kan ?"
    mc "Iya gapapa"
    wkk "ppstt psst... [kk]"
    kk "Apa ?"
    wkk "Giamana mantap kan idenya ?"
    kk "Boleh-boleh"
    na "kalau gitu skuy Pulang"
    mc "...."

    scene jalan
    mg2 "[mcFirst] Maaf Yaa yang kemarin"
    mc "Hahh !?"
    mg2 "Maaff yang Kemarin"
    mc "Ohh.."
    mg2 "Aku juga udah berlebihan nanyain hal yang sensitif"
    mg2 "Bodohnya aku, aku minta maaf yaa.. Hiks... Hikss.."
    mc "Ahh..Iyaa.."
    mc "Aku juga minta maaf kayaknya kemarin aku juga berlebihan"
    mg2 "Kamu ga salah kok"
    mg2 "Aku jika ditanyai hal sensitif begitu terus maksa pasti bakalan marah hehe"
    mc "...."
    mc "dah dah.. kita baikan ?"
    mg2 "Huum Hehehhe"

    scene rumah mg2
    mc "Ini rumahmu kan ?"
    mg2 "Iyaa.. mau mampir ?"
    mc "Ga usah aku pulang dulu aja"
    mg2 "Iyaa.. Hati-hati dijalan yaa"
    mc "Hooh.. iyaa"
    mg2 "bai bai"

    scene depan rumah

    scene ruang tamu
    mc "Aku Pulangg"
    play sound laridilorong
    mom "Gimana kamu gapapa ?"
    mc "Aman buu,, ada Nada juga"
    mom "Syukurlahh"
    mc "Ayah.. kemana bu ?"
    mom "Ayahmu nonton tv"
    mc "ohh.. Iya udah aku mau tidur dulu ya bu"
    mc "aku agak capek bu hehhe"
    mom "Iyaa.."

    scene kamar
    "Huuu Capeknyaaa"
    "Hmm... Kitaa jadi baikan huh"
    "Dahlah aku tidur aja"

    scene kamar malam
    play sound telpon
    "Huhh. siapa ini ?"
    "Ahh.. [mg2_Last]"
    mc "Ada apa ?"
    mg2 "Hoo Sudah bangun kukira masih tidur"
    mc "Kamu telpon aku jadi bangun"
    mg2 "Hehehehe masih capek"
    mc "Ga terlalu sih tapi masih ingin tidur"
    mg2 "Yaudah.. tidur lagi sana"
    mg2 "Ketemu besokk"
    mc "Iyaa Iyaa"
    mg2 "Bai bai"
    mc "Bai"
    "Huu ? kalau gitu aku tidur lagi aja capek beneran ternyata"

label day7_Miselia:

    scene kamar
    mc "Astaghfirullah, sekarang hari senin kah? aku lupa kalo sekarang sekolah"
    mom "Nak, kamu ini sekarang hari senin loh, kamu kok bangunnya siang, apa ga ikut upcara?"
    mc "Aku lupa buk, ku kira sekarang hari minggu , ternyata senin"
    mom "Yasudah segera mandi , ibu siapkan sarapan dulu"
    mc "Iya bukk , aku mandi dulu"

    scene ruang keluarga
    mom "Nak , kali ini ibu tidak masak daging, karena sekarang harga daging melunjak pesat di pasar , mahal banget, makan sama telur aja ya"
    mc "Iyabu, tidakmasalah, yang penting yang masak tu ibu, hehhe"
    mom "Ah kamu ini , sana cepat sarapan, keburu telat nanti"
    mc "Bu aku berangkat sekolah dulu ya , minta doanya semoga hari ini di beri kelancaran dan kemudahan untuk belajar"
    mom "ya nak , ibu selalu mendoakan kamu , supaya jadi orang yang sukses berguna bagi keluarga, nusa dan bangsa"
    mc "Yauda bu , makasi ya , assalamualaikum"

    scene jalan
    mc "Ya Allah, aku sebenernya pengen banget punya sepeda motor, biar bisa brangkat sekolah, ga harus naik angkot ataupun jalan kaki seperti ini"
    kk "Heii , dasar miskin sekolah kok jalan kaki hahha ini udah jaman SMA bre gamalu apa hahha"
    mc "Astaghfirullah haladzim"

    scene lorong kelas 
    $ mln = "Melin"
    mln "Astaga , maaf ya aku ga sengaja"
    mc "Duhh..iyaaa gapapa deh kalo kamu ga sengaja "
    mln "Ya ampun liat baju kamu jadi kotor, sebentar aku ambilin tissue ya"
    mln "Maaf ya kak, aku ga sengaja maaf bnget ya"
    mc "Iya gapapa kok, biar aku bersihin aja ke kamar mandi"
    mln "Btw kamu kelas apa ? kok aku jarang liat kamu ya "
    mc "Aku anak  X MIA  2 , kamu kelas brapa ?"
    mln "Aku melin X IIS 3"
    mg1 "Heh, mgapain kamu di sini ?"
    mc "Ini , tadi melin ga sengaja numpahin minuman ke bajuku "
    mg1 "Hah, ehh kamu kalo jalan pake mata dong , ga liat apa kalo di depan ada orang"
    mln "Maaf kak, aku sudah minta maaf tadi ke dia, dan udah ku beri tissue untuk di bersihkan, tapi dia malah mau ke kamar mandi aja"
    mc "Udah stop, gapapa aku sel, udahhh sekarang mending kita jalan ke kelas aja ayo"
    mln "Sekali lagi aku minta maaf ya mc"
    
    scene depan kelas 
    mc "Misel, tolong taruh kan tas ku dulu ya, aku mau ke toilet dulu untuk membersihkan baju ku ini "
    mg1 "Iya deh,sana buruan "

    scene toilet
    $ dn = "Dani"
    $ ags = "Agus"
    dn "Adudu ada adekelas yang sok tampan ini gengs, enaknya kita apain ya?"
    ags "Hahaha, ganteng ganteng tapi cupu , lu cowo apa cewe nih"
    ags "Eh eh liat liat, mana bajunya udah buluk, eh kena air comberan kali ye hahha"
    mc "Permisi kak , saya mau lewat "
    dn "Sono gih, dasar gembel"
    mc "Ya allah, kenapa ya aku selalu jadi rendahan orang lain, padahal aku gapernah nyari masalah selama ini"

    jump day8_Miselia

 #label day7_Airin:

