#Image(Soal, etc)
image splash = im.Scale("BGSplash.png",1920,1080)
image kucing = im.Scale("1.png", 745,745)
image virusd3 = im.Scale("/Soal/Soal-Virus.jpg",1280,720)
image virusd4_1 = im.Scale("/Soal/Soal_virus.jpg",1280,720)
image virusd4_2 = im.Scale("/Soal/Soal_virus1.jpg",1280,720)
image virusd5 = im.Scale("/Soal/soal_virusd5.jpg",1280,720)
image fungid1 = im.Scale("/Soal/Fungi/Soal_Fungi1.jpg",1280,720)
image fungid2 = im.Scale("/Soal/Fungi/Soal_Fungi2.jpg",720,1280)
image fungid5 = im.Scale("/Soal/Fungi/Soal_Fungi3.jpg",1280,720)

#image BG
image aula = "/background/AULA.png"
image kelas_BnW = "/background/KLH.jpg"
image uks_BnW = "/background/UKSH.jpg"
#Pagi
image sky = "/background/PAGI/SKY.jpg"
image atap = "/background/PAGI/ATP.jpg"
image gerbang_sekolah = "/background/PAGI/GS.jpg"
image kamar = "/background/PAGI/KM.jpg"
image jalan = "/background/PAGI/KT.jpg"
image lorong = "/background/PAGI/LR.png"
image mall = "/background/PAGI/MALL.png"
image ruang_keluarga = "/background/PAGI/RK.png"
image parkir = "/background/PAGI/PK.jpg"
image depan_store = "/background/PAGI/MM.jpg"
image store = "/background/PAGI/DMM.jpg"
image uks = "/background/PAGI/UKS.jpg"
image kantin = "/background/PAGI/KN.jpg"
image pantai = "/background/PAGI/PT.jpg"
image kamar_mandi = "/background/PAGI/BT.jpg"
image central_park = "/background/PAGI/CP.jpg"
image cafe = "/background/PAGI/CF.png"
image ruang_tamu = "/background/PAGI/RT.jpg"
image kelas = "/background/PAGI/KL.jpg"
image foodcourt = "/background/PAGI/FC.jpg"
image depan_toilet = "/background/PAGI/DT.jpg"
image toilet = "/background/PAGI/T.png"
image depan_rumah = "/background/PAGI/DR.png"
image depan_rumah_airin = "/background/PAGI/DRA.png"
image depan_rumah_kirana = "/background/PAGI/DRK.jpg"

#Siang
image depan_toilet_siang = "/background/SIANG/DT.jpg"
image toilet_siang = "/background/SIANG/T.png"
image ruang_tamu_siang = "/background/SIANG/RT.jpg"
image kelas_siang = "/background/SIANG/KL.jpg"
image foodcourt_siang = "/background/SIANG/FC.jpg"
image central_park_siang = "/background/SIANG/CP.jpg"
image cafe_siang = "/background/SIANG/CF.png"
image pantai_siang = "/background/SIANG/PT.jpg"
image kantin_siang = "/background/SIANG/KN.jpg"
image uks_siang = "/background/SIANG/UKS.jpg"
image parkir_siang = "/background/SIANG/PK.jpg"
image jalan_siang = "/background/SIANG/KT.jpg"
image dapur_siang = "/background/SIANG/DPR.jpg"
image atap_siang = "/background/SIANG/ATP.jpg"
image gerbang_sekolah_siang = "/background/SIANG/GS.jpg"
image kamar_siang = "/background/SIANG/KM.jpg"
image lorong_siang = "/background/SIANG/LR.jpg"
image mall_siang = "/background/SIANG/MALL.jpg"
image ruang_keluarga_siang = "/background/SIANG/RK.jpg"
image depan_rumah_siang = "/background/SIANG/DR.png"
image depan_rumah_airin_siang = "/background/SIANG/DRA.png"
image depan_rumah_kirana_siang = "/background/SIANG/DRK.jpg"

#Sore
image depan_toilet_sore = "/background/SORE/DT.jpg"
image toilet_sore = "/background/SORE/T.png"
image ruang_tamu_sore = "/background/SORE/RT.jpg"
image kelas_sore = "/background/SORE/KL.jpg"
image foodcourt_sore = "/background/SORE/FC.jpg"
image central_park_sore = "/background/SORE/CP.jpg"
image cafe_sore = "/background/SORE/CF.png"
image kantin_sore = "/background/SORE/KN.jpg"
image uks_sore = "/background/SORE/UKS.jpg"
image parkir_sore = "/background/SORE/PK.jpg"
image dapur_sore = "/background/SORE/DPR.jpg"
image atap_sore = "/background/SORE/ATP.jpg"
image gerbang_sekolah_sore = "/background/SORE/GS.jpg"
image jalan_sore = "/background/SORE/KT.jpg"
image kamar_sore = "/background/SORE/KM.jpg"
image lorong_sore = "/background/SORE/LR.jpg"
image mall_sore = "/background/SORE/MALL.png"
image ruang_keluarga_sore = "/background/SORE/RK.jpg"
image pantai_sore = "/background/SORE/PT.jpg"
image depan_rumah_sore = "/background/SORE/DR.png"
image depan_rumah_airin_sore = "/background/SORE/DRA.png"
image depan_rumah_kirana_sore = "/background/SORE/DRK.jpg"

#Malam
image depan_toilet_malam = "/background/MALAM/DT.jpg"
image toilet_malam = "/background/MALAM/T.png"
image ruang_tamu_malam = "/background/MALAM/RT.jpg"
image kelas = "/background/MALAM/KL.jpg"
image foodcourt_malam = "/background/MALAM/FC.jpg"
image pantai_malam = "/background/MALAM/PT.jpg"
image kantin_malam = "/background/MALAM/KN.jpg"
image uks_malam = "/background/MALAM/UKS.jpg"
image dapur_malam = "/background/MALAM/DPR.jpg"
image atap_malam = "/background/MALAM/ATP.jpg"
image gerbang_sekolah_malam = "/background/MALAM/GS.jpg"
image kamar_malam = "/background/MALAM/KM.jpg"
image jalan_malam = "/background/MALAM/KT.jpg"
image lorong_malam = "/background/MALAM/LR.jpg"
image mall_malam = "/background/MALAM/MALL.png"
image ruang_keluarga_malam = "/background/MALAM/RK.jpg"
image section_baju_malam = "/background/MALAM/SB.jpg"
image parkiran_mall_malam = "/background/MALAM/IPK.jpg"
image kamar_mandi_malam = "/background/MALAM/BT.jpg"
image central_park_malam = "/background/MALAM/CP.jpg"
image cafe_malam = "/background/MALAM/CF.jpg"
image depan_rumah_malam = "/background/MALAM/DR.png"
image depan_rumah_airin_malam = "/background/MALAM/DRA.png"
image depan_rumah_kirana_malam = "/background/MALAM/DRK.jpg"

#Image(Character)
image mom = im.Scale("/Character/mom/mom.png", 400, 1050)
image dad_uni = im.Scale("/Character/dad/dad_uni.png", 625, 1181)
image dad_cas = im.Scale("/Character/dad/dad_cas.png", 625, 1181)
image cat_angry = im.Scale("/Character/Feliz/angry_cat.png", 350, 650)
image cat_happy = im.Scale("/Character/Feliz/happy_cat.png", 300, 450)
image cat = im.Scale("/Character/Feliz/cat.png", 350, 650)
image cat_box = im.Scale("/Character/Feliz/cat_box1.png", 350, 650)
image cat_box_happy = im.Scale("/Character/Feliz/cat_box2.png", 350, 650)
image cat_box_relived = im.Scale("/Character/Feliz/cat_box3.png", 350, 650)
image ardana_cas = im.Scale("/Character/ardana/ardana_cas.png", 625, 1100)
image ardana_uni = im.Scale("/Character/ardana/ardana_uni.png", 625, 1100)
image ardana_uni_emosi = im.Scale("/Character/ardana/ardana_uni_emosi.png", 625, 1100)
image ardana_uni_cuek = im.Scale("/Character/ardana/ardana_uni_cuek.png", 625, 1100)
image miselia_casual = im.Scale("/Character/miselia/miselia_cas.png", 625, 1100)
image miselia_uni = im.Scale("/Character/miselia/miselia_uni.png", 625, 1100)
image airin_casual = "/Character/airin/airin_cas.png"
image airin_uni = im.Scale("/Character/airin/airin_uni.png", 625, 1100)
image airin_kaget_uni = "/Character/prolog/airin_kaget_uni.png"
image airin_jalan_uni = "/Character/prolog/airin_jalan_uni.png"
image nada_uni = im.Scale("/Character/sahabat/Nada_uni.png", 700, 1181)
image nada_cas = im.Scale("/Character/sahabat/Nada_Casual.png", 700, 1181)
image bu_senda = im.Scale("/Character/Bu_Senda/senda.png", 625, 1181)